### ISSUE TITLE
could you please send me the data files, thank

### ISSUE THREAD

**Issue by liamxg** [clifmckee/thai-bats-bartonella#1]

**Comment by clifmckee** [comment]
Which data files are you looking for? Is there a particular piece of the code that you are trying to run?

The sequence data was all published on GenBank and the accession numbers were provided in the manuscript.

**Comment by LiXingguangBrandonStark** [comment]
Thailand1=readRDS("THA_adm1.rds"), this THA_adm1.rds, thanks.

**Comment by LiXingguangBrandonStark** [comment]
THA_adm1.rds,this file, thanks.
