### ISSUE TITLE
how to set value +1.5 in "Thailand1@polygons[[55]]@labpt[1]+1.5" ?

### ISSUE THREAD

**Issue by liamxg** [clifmckee/thai-bats-bartonella#3]
@clifmckee

**Comment by clifmckee** [comment]
All of these numbers in this block of code are small modifiers to move the text labels on the map. I wanted them to be far enough away from the map so the labels didn't overlap the country borders too much. Setting the number values is just a process of trial and error. I had to render the map multiple times and change the values to move things around until I was satisfied with how it looked.

**Comment by liamxg** [comment]
@clifmckee thanks for your kind reply.
