### ISSUE TITLE
Is it necessary to use the function "m.prevalence = melt(prevalence[, 1:3])" in "Thailand_mapping.R" file?

### ISSUE THREAD

**Issue by liamxg** [clifmckee/thai-bats-bartonella#6]
ggplot(data = prevalence, aes(x = Province, y = Count, group = Species, fill = Species)) +
  geom_bar(stat = "identity") +
  theme_classic(base_size = 12) +
  ylim(0, 45) +
  ylab("Count") +
  scale_fill_brewer(palette ="Dark2") +
  theme(axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(colour = 'black'),
        axis.ticks.y = element_line(colour = 'black'),
        axis.title.x = element_text(colour = 'black'),
        axis.title.y = element_text(colour = 'black'),
        panel.border = element_rect(colour = 'black', fill = NA),
        axis.text.x = element_text(angle = 0, colour = 'black'))

**Comment by liamxg** [comment]
I use the prevalence data to get the same results.

**Comment by clifmckee** [comment]
I guess not. I think the CSV data file is already structured in a way that `ggplot` can interpret, so the `melt` processing isn't really necessary. It's hard to remember since I wrote this code over 6 years ago.

**Comment by liamxg** [comment]
@clifmckee agree. So I updated your script for myself.
